version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    working_directory: /tmp/build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container
          command: |
            TAG="${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM}"
            docker build -t michielrensen/docker-build:$TAG -t michielrensen/docker-build:latest .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker tag michielrensen/docker-build:$TAG michielrensen/docker-build:latest
            fi
      - deploy:
          command: |
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
            docker push michielrensen/docker-build
