version: 2
jobs:
  build:
    docker:
      - image: docker
    working_directory: /tmp/build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container
          command: |
            TAG="v${CIRCLE_BUILD_NUM}"
            docker build -t michielrensen/docker-build:$TAG -t michielrensen/docker-build:latest .
      - deploy:
          command: |
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
            docker push michielrensen/docker-build
